version: '3'
services:
  api-server:
    image: api-server
    build: ./Server
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: api-server
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge