version: '3'
services:

  api-server:
    image: api-server
    build:
      context: ./Server
      args:
        SERVER_PORT: "${SERVER_PORT}"
    env_file: .env
    networks:
      - backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./Server:/usr/src/app

  postgres:
    image: postgres:14-alpine
    env_file: .env
    networks:
      - backend
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./DB/scripts/00-stackoverfaux.json:/docker-entrypoint-initdb.d/00-stackoverfaux.json
      - ./DB/scripts/01-create.sql:/docker-entrypoint-initdb.d/01-create.sql
      - ./DB/scripts/02-ETL.sql:/docker-entrypoint-initdb.d/02-ETL.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

networks:
  backend:
    driver: bridge