version: '3'
services:
  api-server:
    image: api-server
    build: ./Server
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./Server:/usr/src/app
networks:
  backend:
    driver: bridge